# Generated by Django 5.2.4 on 2025-07-16 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('other_titles', models.CharField(blank=True, max_length=255)),
                ('connect', models.TextField(blank=True)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('level_winter', models.CharField(blank=True, max_length=3)),
                ('level_summer', models.CharField(blank=True, max_length=3)),
                ('level_autumn', models.CharField(blank=True, max_length=3)),
                ('level_spring', models.CharField(blank=True, max_length=3)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('pending', 'На модерации'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=10)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pereval', to='NewPereval.coords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perevals', to='NewPereval.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='NewPereval.pereval')),
            ],
        ),
    ]
